<?php
$lamps = array(
    array('image' => 'images/GE_cp92.JPG',
        'product_name' => 'General Electric CP92',
        'product_desc' => '1500 Рублей',
        'param_n' => '230V',         // Напряжение
        'param_m' => '2000W',       // Мощьность
        'param_tc' => 'G22',      //цоколя
        'param_l' => 'Halogen',       // Цена
        'param_n_hid' => '400 h ',     // hidden срок службы
        'param_m_hid' => '3200К',   // hidden цветовая температура
        'param_tc_hid' => '52000lm',  // hidden  световой поток
        'param_l_hid' => 'UK',   // hidden страна производитель
        'product_sale' => '-30%'
        ),
    array('image' => 'images/GE_T26.JPG',
        'product_name' => 'General Electric T26 GCS',
        'product_desc' => '800 Рублей',
        'param_n' => '240V',         // Напряжение
        'param_m' => '650W',       // Мощьность
        'param_tc' => 'GY9.5',      //цоколя
        'param_l' => 'Halogen',       // Цена
        'param_n_hid' => '400 h ',     // hidden срок службы
        'param_m_hid' => '3100К',   // hidden цветовая температура
        'param_tc_hid' => '15500lm',  // hidden  световой поток
        'param_l_hid' => 'EU',   // hidden страна производитель
        'product_sale' => '-40%'
    ),array('image' => 'images/GE_T27.JPG',
        'product_name' => 'General Electric T27',
        'product_desc' => '800 Рублей',
        'param_n' => '230V',         // Напряжение
        'param_m' => '650W',       // Мощьность
        'param_tc' => 'GY9.5',      //цоколя
        'param_l' => 'Halogen',       // Цена
        'param_n_hid' => '400 h ',     // hidden срок службы
        'param_m_hid' => '3050К',   // hidden цветовая температура
        'param_tc_hid' => '14500lm',  // hidden  световой поток
        'param_l_hid' => 'UK',   // hidden страна производитель
        'product_sale' => '-40%'
    ),array('image' => 'images/Osram_hpl_750.jpg',
        'product_name' => 'OSRAM HPL 750/240',
        'product_desc' => '1000 Рублей',
        'param_n' => '240V',         // Напряжение
        'param_m' => '750W',       // Мощьность
        'param_tc' => 'G9.5',      //цоколя
        'param_l' => 'Halogen',       // Цена
        'param_n_hid' => '300 h ',     // hidden срок службы
        'param_m_hid' => '3200К',   // hidden цветовая температура
        'param_tc_hid' => '17950lm',  // hidden  световой поток
        'param_l_hid' => 'Mexico',   // hidden страна производитель
        'product_sale' => '-25%'
    ),array('image' => 'images/Philips cp70.JPG',
        'product_name' => 'Philips Broadway CP70',
        'product_desc' => '1180 Рублей',
        'param_n' => '230V',         // Напряжение
        'param_m' => '1000W',       // Мощьность
        'param_tc' => 'GX9.5',      //цоколя
        'param_l' => 'Halogen',       // Цена
        'param_n_hid' => '240 h ',     // hidden срок службы
        'param_m_hid' => '3200К',   // hidden цветовая температура
        'param_tc_hid' => '25000lm',  // hidden  световой поток
        'param_l_hid' => 'France',   // hidden страна производитель
        'product_sale' => '-25%'
    ),array('image' => 'images/sylvania.jpg',
        'product_name' => 'Sylvania HSW 400',
        'product_desc' => '3100 рублей',
        'param_n' => '135V',         // Напряжение
        'param_m' => '400W',       // Мощьность
        'param_tc' => 'E40',      //цоколя
        'param_l' => 'UV',       // Цена
        'param_n_hid' => '2000 h ',     // hidden срок службы
        'param_m_hid' => '',   // hidden цветовая температура
        'param_tc_hid' => '',  // hidden  световой поток
        'param_l_hid' => 'China',   // hidden страна производитель
        'product_sale' => '-20%'
    ),
);
